pond_array = [[["rot_thinrec1", "rot_thinrec2"], [7]],
[["zigzag1", "zigzag2"], [22]],
[["dualDiamonds1", "dualDiamonds2"], [28]],
[["rot_widerec1", "rot_widerec2"], [8]],
[["upsidedown_L1", "upsidedown_L2"], [9]],
[["croissant1", "croissant2"], [13]],
[["set1_rotY1", "set1_rotY2"], [29]],
[["set2_rotY1", "set2_rotY2"], [15]],
[["set1_rotarrow1", "set1_rotarrow2"], [23]],
[["set2_rotarrow1", "set2_rotarrow2"], [24]],
[["T2", "T1"], [1]],
[["sideways_T1", "sideways_T2"], [16]],
[["sideways_L1", "sideways_L2"], [2]],
[["upwardpointing_L", "downwardpointing_L"], [17]],
[["n1", "n2"], [3]],
[["sideways_n1", "sideways_n2"], [19]],
[["trapezoid2", "trapezoid1"],[4]],
[["sideways_trap1", "sideways_trap2"], [18]],
[["upright_croissant", "downward_croissant"], [30]],
[["sideways_croissant1", "sideways_croissant2"], [14]],
[["thin_rec1", "thin_rec2"], [6]],
[["upright_thinrec1", "upright_thinrec2"], [21]],
[["sideways_H1", "sideways_H2"], [5]],
[["H1", "H2"], [20]],
[["horiz_bowtie1", "horiz_bowtie2"], [10]],
[["upright_bowtie1", "upright_bowtie2"], [25]],
[["donut1", "donut2"], [12, 27]],
[["square1", "square2"], [11, 26]]]

names = ["rot_thinrecs", "zigzags", "Diamonds", "rot_widerecs", "upsidedown_L's", "croissants", "set1_rotY's",
"set2_rotY's", "set1_rotarrows", "set2_rotarrows", "T's", "sideways_T's", "sideways_L's", "vertical_L's",
"n's", "sideways_n's", "trapezoids", "sideways_trap's", "vertical_croissants", "sideways_croissants", "horiz_thin_recs", 
"upright_thin_recs", "sidways_H's", "upright_H's", "horiz_bowties", "upright_bowties", "donuts", "squares"]